const express=require('express');const{query}=require('../db');const{authenticate,requireAdmin}=require('../middleware/auth');const router=express.Router();
router.use(authenticate,requireAdmin);
router.get('/stats',async(req,res)=>{try{const[users,payments,enrollments,revenue]=await Promise.all([query("SELECT COUNT(*) AS n FROM users WHERE role=$1",['student']),query('SELECT COUNT(*) AS n FROM payments'),query('SELECT COUNT(*) AS n FROM enrollments'),query("SELECT COALESCE(SUM(amount_idr),0) AS total FROM payments WHERE status='paid'")]);res.json({total_members:parseInt(users.rows[0].n),total_payments:parseInt(payments.rows[0].n),total_enrollments:parseInt(enrollments.rows[0].n),total_revenue_idr:parseInt(revenue.rows[0].total)});}catch(err){res.status(500).json({error:'Internal server error'});}});
router.get('/members',async(req,res)=>{try{const{rows}=await query(`SELECT u.id,u.name,u.email,u.role,u.created_at,COUNT(DISTINCT e.course_id) AS courses_enrolled,COALESCE(SUM(CASE WHEN p.status='paid' THEN p.amount_idr ELSE 0 END),0) AS total_spent FROM users u LEFT JOIN enrollments e ON e.user_id=u.id LEFT JOIN payments p ON p.user_id=u.id GROUP BY u.id ORDER BY u.created_at DESC`);res.json({members:rows});}catch(err){res.status(500).json({error:'Internal server error'});}});
router.get('/payments',async(req,res)=>{try{const{rows}=await query(`SELECT p.*,u.name AS user_name,u.email AS user_email,c.title AS course_title,c.slug AS course_slug FROM payments p JOIN users u ON u.id=p.user_id JOIN courses c ON c.id=p.course_id ORDER BY p.created_at DESC`);res.json({payments:rows});}catch(err){res.status(500).json({error:'Internal server error'});}});

// GET /api/admin/courses - list all courses
router.get('/courses',async(req,res)=>{try{const{rows}=await query('SELECT id,slug,title,lesson_count,is_active FROM courses ORDER BY id ASC');res.json({courses:rows});}catch(err){res.status(500).json({error:'Internal server error'});}});

// GET /api/admin/courses/:slug/lessons - get lesson content for a course
router.get('/courses/:slug/lessons',async(req,res)=>{try{const{rows:cr}=await query('SELECT id FROM courses WHERE slug=$1',[req.params.slug]);if(!cr.length)return res.status(404).json({error:'Course not found'});const courseId=cr[0].id;const{rows}=await query('SELECT lesson_index,youtube_url FROM lesson_content WHERE course_id=$1 ORDER BY lesson_index ASC',[courseId]);res.json({lessons:rows});}catch(err){res.status(500).json({error:'Internal server error'});}});

// PUT /api/admin/courses/:slug/lessons - bulk upsert lesson youtube urls
router.put('/courses/:slug/lessons',async(req,res)=>{try{const{rows:cr}=await query('SELECT id FROM courses WHERE slug=$1',[req.params.slug]);if(!cr.length)return res.status(404).json({error:'Course not found'});const courseId=cr[0].id;const lessons=req.body.lessons||[];for(const l of lessons){if(typeof l.lesson_index!=='number')continue;await query(`INSERT INTO lesson_content(course_id,lesson_index,youtube_url,updated_at) VALUES($1,$2,$3,NOW()) ON CONFLICT(course_id,lesson_index) DO UPDATE SET youtube_url=$3,updated_at=NOW()`,[courseId,l.lesson_index,l.youtube_url||null]);}res.json({ok:true,updated:lessons.length});}catch(err){res.status(500).json({error:'Internal server error'});}});

module.exports=router;
