const express=require('express');const{query}=require('../db');const{optionalAuth}=require('../middleware/auth');const router=express.Router();
router.get('/',optionalAuth,async(req,res)=>{const{track}=req.query;try{let sql='SELECT * FROM courses WHERE is_active=1';const params=[];if(track){sql+=' AND track=$1';params.push(track);}sql+=' ORDER BY id ASC';const{rows:courses}=await query(sql,params);let enrolled=new Set();if(req.user){const{rows}=await query('SELECT course_id FROM enrollments WHERE user_id=$1',[req.user.id]);enrolled=new Set(rows.map(r=>r.course_id));}const data=courses.map(c=>({...c,enrolled:enrolled.has(c.id)}));res.json({courses:data});}catch(err){res.status(500).json({error:'Internal server error'});}});
router.get('/:slug',optionalAuth,async(req,res)=>{try{const{rows}=await query('SELECT * FROM courses WHERE slug=$1 AND is_active=1',[req.params.slug]);const course=rows[0];if(!course)return res.status(404).json({error:'Course not found'});let isEnrolled=false;if(req.user){const{rows:er}=await query('SELECT id FROM enrollments WHERE user_id=$1 AND course_id=$2',[req.user.id,course.id]);isEnrolled=er.length>0;}res.json({course:{...course,enrolled:isEnrolled}});}catch(err){res.status(500).json({error:'Internal server error'});}});

// GET /api/courses/:slug/lesson-content - public, returns stored youtube URLs per lesson index
router.get('/:slug/lesson-content',async(req,res)=>{try{const{rows:cr}=await query('SELECT id FROM courses WHERE slug=$1 AND is_active=1',[req.params.slug]);if(!cr.length)return res.status(404).json({error:'Course not found'});const{rows}=await query('SELECT lesson_index,youtube_url FROM lesson_content WHERE course_id=$1',[cr[0].id]);res.json({lessons:rows});}catch(err){res.status(500).json({error:'Internal server error'});}});

// GET /api/courses/:slug/attachments - public
router.get('/:slug/attachments',async(req,res)=>{try{const{rows:cr}=await query('SELECT id FROM courses WHERE slug=$1 AND is_active=1',[req.params.slug]);if(!cr.length)return res.status(404).json({error:'Course not found'});const{rows}=await query('SELECT id,lesson_index,display_name,file_type,cloudinary_url,file_size FROM lesson_attachments WHERE course_id=$1 ORDER BY lesson_index,created_at ASC',[cr[0].id]);res.json({attachments:rows});}catch(err){res.status(500).json({error:'Internal server error'});}});

module.exports=router;
